### ISSUE TITLE
Initial configuration wizard not working on Android Web UI

### ISSUE THREAD

**Issue by jeremypoulter** [KipK/openevse-gui-v2#18]
Just tried the initial configuration wizard (just happened to be install on a new device) and it did not move through the screen. This is with the PR to embed in the firmware.

**Comment by jeremypoulter** [comment]
https://photos.app.goo.gl/7pC41qyv9UZehgkU7

**Comment by KipK** [comment]
Ho I haven't tried yet to embedded it in esp  
But I've fixed some stuff already yesterday on this.

Have you modified the webserver_static.cpp to get index.html for all request instead of home.html + wifiportal.html ?

edit: I've just seen your last modif here https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/487/commits/71e2a1db86d85d1e0cee70e950dc9f5b12eaf357
I will  test that asap
