### ISSUE TITLE
FR: Simultaneous Active Limits

### ISSUE THREAD

**Issue by fhteagle** [KipK/openevse-gui-v2#27]
Per RC3 issue thread, splitting this here:

It may be useful for some users to be able to set multiple limits, and pause on whichever is reached first.

**Comment by pdhoogh** [comment]
Agreed. A practical case I would like to be able to do is charging in "Fast" mode with a system limit of e.g. 16 Amps and using the Shaper set to e.g. 2500 Watt.  I tried this in 4.1.5 but that did not work. I believe it still doesn't.
![image](https://user-images.githubusercontent.com/105557142/220972885-5c44c472-f036-49c9-8a64-fe6c3b8fe618.png)

What happens if ECO mode is used and Shaper is still enabled?  That also did not seem to work well last year.

**Comment by KipK** [comment]
I'm pretty sure you can't set the same mqtt topic for booth shaper & divert on current implementation. 
But it's out of topic here, @fhteagle talks about charge limit feature. 

@fhteagle , I'll keep a simple one limit per session for now. We'll see later if it really has some real use case.
